const SELECT_DAY = 'SELECT_DAY';
const SELECT_TASK = 'SELECT_TASK';
const CHANGE_MODAL_STATE = 'CHANGE_MODAL_STATE';
const ADD_TASK = 'ADD_TASK';
const UPDATE_TASK = 'UPDATE_TASK';

export {
    SELECT_DAY,
    SELECT_TASK,
    CHANGE_MODAL_STATE,
    ADD_TASK,
    UPDATE_TASK
};
